jenkins:
    build: jenkins
    user: ${USER_ID}
    volumes:
        - ./home:/var/jenkins_home

git:
    build: git
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres
    volumes:
        - ./pgdata:/var/lib/postgresql/data

testintegration:
    extends:
        file: common-services-v1.yml
        service: baseslave
    links:
        - jenkins
        - pg
        - seleniumhub
    volumes:
        - ./slave:/home/omero
    environment:
        - SLAVE_NAME=testintegration
        - SLAVE_PARAMS=-labels centos7 -labels ice36 -labels java18 -disableClientsUniqueId
    extra_hosts:
        - "testintegration:127.0.0.1"

omero:
    extends:
        file: common-services-v1.yml
        service: baseserver
    links:
        - jenkins
        - pg
    volumes:
        - ./server:/home/omero
    environment:
        - SLAVE_NAME=omero
        - SLAVE_PARAMS=-labels centos7 -labels ice36 -labels java18 -disableClientsUniqueId

web:
    extends:
        file: common-services-v1.yml
        service: baseweb
    links:
        - jenkins
        - redis
        - omero
        - testintegration
    volumes:
        - ./web:/home/omero
        - ./nginx/conf.d:/home/omero/nginx
    environment:
        - SLAVE_NAME=web
        - SLAVE_PARAMS= -labels centos7 -labels ice36 -labels java18 -disableClientsUniqueId

nginx:
    extends:
        file: common-services-v1.yml
        service: basenginx
    links:
        - jenkins
        - web
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./web/static:/home/omero/static
        - ./nginx/log:/var/log/nginx
        - ./nginx/sslcert:/etc/nginx/ssl
    environment:
        - SLAVE_NAME=nginx
        - SLAVE_PARAMS=-labels centos7 -labels java18 -disableClientsUniqueId

nginxjenkins:
    image: nginx:1.10
    links:
        - jenkins
    volumes:
        - ./jenkins/conf.d:/etc/nginx/conf.d
        - ./jenkins/sslcert:/etc/nginx/ssl

redis:
    image: redis

seleniumhub:
    image: selenium/hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
        - GRID_BROWSER_TIMEOUT=30000
        - GRID_TIMEOUT=30000
seleniumfirefox:
    image: selenium/node-firefox
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
seleniumchrome:
    image: selenium/node-chrome
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
