jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home

git:
    build: git
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres
    volumes:
        - ./services/pgdata:/var/lib/postgresql/data

omero:
    extends:
        file: common-services.yml
        service: baseserver
    links:
        - jenkins
        - pg
    volumes:
        - ./services/omero:/home/omero
    environment:
        - SLAVE_NAME=omero
        - SLAVE_PARAMS=-labels centos7 -labels ice36 -disableClientsUniqueId

testintegration:
    extends:
        file: common-services.yml
        service: baseslave
    links:
        - jenkins
    volumes:
        - ./services/testintegration:/home/omero
    environment:
        - SLAVE_NAME=testintegration
        - SLAVE_PARAMS=-labels centos7 -labels ice36 -disableClientsUniqueId

web:
    extends:
        file: common-services.yml
        service: baseweb
    links:
        - jenkins
        - redis
        - omero
        - testintegration
    volumes:
        - ./services/web:/home/omero
        - ./services/nginx/conf.d:/home/omero/nginx
    environment:
        - SLAVE_NAME=web
        - SLAVE_PARAMS= -labels centos7 -labels ice36 -disableClientsUniqueId

nginx:
    extends:
        file: common-services.yml
        service: basenginx
    links:
        - jenkins
        - web
    volumes:
        - ./services/nginx/conf.d:/etc/nginx/conf.d
        - ./services/web/static:/home/omero/static
    environment:
        - SLAVE_NAME=nginx
        - SLAVE_EXECUTORS=1
        - SLAVE_PARAMS=-labels centos7 -disableClientsUniqueId

redis:
    image: redis

seleniumhub:
    image: selenium/hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
        - GRID_BROWSER_TIMEOUT=5000
        - GRID_TIMEOUT=5000
seleniumfirefox:
    image: selenium/node-firefox
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
seleniumchrome:
    image: selenium/node-chrome
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
