jenkins:
    build: jenkins
    user: ${USER_ID}
    volumes:
        - ./home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        #- ${WHICH_DOCKER}:/usr/bin/docker
    environment:
        - JENKINS_OPTS= --argumentsRealm.passwd.${JENKINS_USERNAME}=${JENKINS_PASSWORD} --argumentsRealm.roles.${JENKINS_USERNAME}=admin

nginxjenkins:
    image: nginx:1.10
    links:
        - jenkins
    volumes:
        - ./jenkins/conf.d:/etc/nginx/conf.d
        - ./jenkins/sslcert:/etc/nginx/ssl
    ports:
        - "8443:443"
