jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home
    environment:
        - SERVICE_NAME=devspace_web-ci

git:
    build: git
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres

slave:
    build: slave
    links:
        - pg
        - jenkins
    volumes:
        - ./slave:/home/slave
    volumes_from:
        - git
    environment:
        - JAVA_HOME=/etc/alternatives/java_sdk
        - SERVICE_NAME=devspace_web-omero
    ports:
        - "4064:4064"
        - "4063:4063"

nginx:
    image: nginx
    links:
        - slave
    volumes:
        - ./slave:/home/jenkins-slave
    environment:
        - SERVICE_NAME=devspace_web-web
