jenkins:
    user: ${USER_ID}
    ports:
        - "443:8443"

testintegration:
    ports:
        - "14064:14064"
        - "14063:14063"
omero:
    ports:
        - "4064:4064"
        - "4063:4063"
nginx:
    ports:
        - "80:80"
        - "443:443"
seleniumhub:
    ports:
        - "4444:4444"
