---
# Playbook for starting a docker instance in the
# openstack cloud.

## Run:
# $ source openrc.sh
# $ ansible-playbook provision.yml -e prefix=prefix -e key_name=your_key

- hosts: localhost
  connection: local

  vars:
    network_name: "{{ prefix }}_network"

  pre_tasks:

    - fail:
        msg: "key_name is required"
      when: key_name is undefined or not key_name

    - fail:
        msg: "prefix is required"
      when: prefix is undefined or not prefix

    - name: Create new keypair from current user's default SSH key
      os_keypair:
        state: present
        name: "{{ key_name }}"
        public_key_file: "{{ '~' | expanduser }}/.ssh/id_rsa.pub"


  roles:

    - role: network
      network_subnet: 10.0.2.0/24
      network_dns: [8.8.8.8]
      network_gateway: 10.0.2.1
      subnet_name: "{{ prefix }}_subnet"
      router_name: "{{ prefix }}_router"

    - role: create_vm
      with_items:
        - "master"
      include_role:
        name: "create_vm"
      vars:
        key_name: "{{ key_name }}"
        vm_name: "{{ prefix }}_master"
        vm_image: "Centos 7"
        vm_groups: "ansible-managed,os-image-centos"
        vm_flavour_ram: 32000
        vm_size: 100
        vm_group_name: "{{ prefix }}-master"
        security_group_name: "{{ prefix }}-external"
        ansible_user: centos


- hosts: "{{ prefix }}-master-hosts"

  vars_prompt:
    - name: "devspace_jenkins_password"
      prompt: "To secure access to Jenkins enter a password for user: devspace"
      private: yes

  pre_tasks:

    - fail:
        msg: "Password to secure access to Jenkins is required"
      when: devspace_jenkins_password is undefined or not devspace_jenkins_password

  roles:

    - role: openmicroscopy.docker
      docker_groupmembers: [centos]
      docker_install_upstream: False
      docker_use_ipv4_nic_mtu: False

    - role: openmicroscopy.devspace
      # Path to SSH and Git configuration files e.g. ~/devspace_training
      configuration_dir_path: "./"
      # The name of the git branch all the jobs will be using. The default is develop
      # devspace_omero_branch: develop
      # The devspace repository to use. The default is https://github.com/openmicroscopy/devspace.git
      # devspace_git_repo: https://github.com/openmicroscopy/devspace.git
      # The devspace branch to use. The default is the latest released version
      # devspace_git_repo_version: "0.5.2"
      # force a clean
      devspace_git_update: yes
      devspace_git_force: yes
      git_user: "olatarkowska"
      devspace_omero_branch: "develop"
      devspace_git_repo: "https://github.com/olatarkowska/devspace.git"
      devspace_git_repo_version: "master"
      omero_server_ssl: 4064
      omero_server_tcp: 4063
      nginx_port: 80
      nginx_ssl_port: 443
