---
# Exampe Playbook for provisioning Devspace
# Minimally modify the following two parameters under roles:
# configuration_dir_path should be the path to your .ssh directory usually ~
# github_user is the GitHub username associated to the .ssh and configuration file

- hosts: all

  vars_prompt:
    - name: "devspace_jenkins_password"
      prompt: "To secure access to Jenkins enter a password for user: devspace"
      private: yes

  pre_tasks:

    - fail:
        msg: "Password to secure access to Jenkins is required"
      when: devspace_jenkins_password is undefined or not devspace_jenkins_password

  roles:
    - role: openmicroscopy.docker
      docker_use_ipv4_nic_mtu: True
    - role: openmicroscopy.devspace
      # Path to SSH and Git configuration files e.g. ~/devspace_training
      configuration_dir_path: "path/to/devspace_training/.ssh"
      # The name of the git branch all the jobs will be using. The default is develop
      # devspace_omero_branch: develop
      # The devspace repository to use. The default is https://github.com/openmicroscopy/devspace.git
      # devspace_git_repo: https://github.com/openmicroscopy/devspace.git
      # The devspace branch to use. The default is the latest released version
      # devspace_git_repo_version: "0.5.2"
      # force a clean
      devspace_git_update: yes
      devspace_git_force: yes
