# External Ansible roles required by this repository

- src: openmicroscopy.basedeps
  version: 1.0.0

- src: openmicroscopy.devspace
  version: 0.2.1

- src: openmicroscopy.docker
  version: 3.0.0

- src: openmicroscopy.docker-tools
  version: 1.0.0

- src: openmicroscopy.local-accounts
  version: 1.0.1

- src: openmicroscopy.upgrade-distpackages
  version: 1.0.0

- src: openmicroscopy.versioncontrol-utils
  version: 1.0.0

# External development roles

- src: openmicroscopy.omero-user
  version: 0.1.0
